title: Cezary Pilaszewicz's Homepage
page-top-title: Cezary Pilaszewicz
top-section-bg-text: Dr. Cezary Pilaszewicz
home-subtitle: IT Security Expert
copyright-text: '&copy; Cezary Pilaszewicz 2025. All Rights Reserved.'
